const: 
  hc : 197.3269804
  u : 931.49410242
  e2 : 1.43996448
  R_MAX : 25.0
  kappa_fixed : 0.639
  r0_so_fixed : 1.16
  a_so_fixed : 0.662


experiment:
  A: 56
  Z: 28
  is_proton: False
  max_states : 7
  n_r_points: 96
  Nr_norm: 1024
  Nth_norm: 512
  Nph_norm: 512
  
  

training:
  epochs : 15.000
  lr_wave: 0.0005
  lr_param: 0.001
  hidden_wave: 256
  hidden_param: 256
  emm: 0
  wE: 50.0
  wR: 5.0
  wTh: 5.0
  wPh: 5.0
  wBC: 5.0
  wORTH: 5.0
  wKL: 0.001
  use_scheduler_wave: True
  use_scheduler_param: True
  gamma_wave: 0.6
  gamma_param: 0.5
  step_size_wave: 1000
  step_size_param: 1500
  print_every: 100




